version: '2'
services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.3-debian-10'
    environment:
      - MARIADB_ROOT_PASSWORD=takenfrombitnami
    volumes:
      - './mariadb_data:/bitnami'
  phpmyadmin:
    image: 'docker.io/bitnami/phpmyadmin:5-debian-10'
    ports:
      - '8038:8080'
      - '4438:8443'
    depends_on:
      - mariadb
    volumes:
      - './phpmyadmin_data:/bitnami'
  skyblock:
    build: .
    ports:
    - "8108:8008"
    volumes:
    - ./ah:/data
    - ./import:/import
    restart: always
    depends_on:
      - mariadb
  redis:
    image: "redis:alpine"
    environment:
      - REDIS_REPLICATION_MODE=master
 

